analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates
cookie_consent_form:
  enabled: false
country:
  name: Aruba
  adjective: Aruban
create_goals:
  previous_next_links: false
  goal_content_heading: ''
  goals: []
create_indicators:
  previous_next_links: false
create_pages:
  - filename: ''
    folder: /goals
    layout: goals
    title: general.goals
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: ''
    folder: /search
    layout: search
    title: search.search
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: data
data_fields:
  units: ''
  series: ''
date_formats: []
disclaimer:
  phase: 'BETA'
  message: 'This is the initial site where the indicators of Aruba will be published.'
  hidden: false
email_contacts:
  questions: cbs@setarnet.aw  
  suggestions:  cbs@setarnet.aw  
  functional:  cbs@setarnet.aw  
empty_metadata_placeholder: 'No metadata available yet'
empty_metadata_placeholder_sources: 'No metadata about sources'
environment: staging
footer_language_toggle: none
footer_menu:
  - path: /contact-us
    translation_key: menu.contact_us
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: Promosi 
    content: |
      This is a proprietary system developed by Central Bureau Of Statistics (CBS) Aruba to monitor the production process of the indicators within CBS. The name is deducted from <i>Pro</i>duction <i>Mon</i>itoring <i>S</i>DG <i>i</i>ndicator (Promosi)
    include: ''
    button_label: Read more
    button_link: 'https://example.com'
    rule_color: ''
  - title: Open SDG used by Aruba
    content: |
      Beside the Promosi system CBS Aruba used the OpenSdg instance to publish the data of the indicators produced.
    include: ''
    button_label: Read more
    button_link: 'https://example.com'
    rule_color: ''
frontpage_goals_grid:
  title: frontpage.heading_short
  description: frontpage.instructions_shorter
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: frontpage.intro_body
goal_image_base: 'https://open-sdg.org/sdg-translations/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: general.goals
  description: frontpage.instructions_shorter
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: true
header_language_toggle: dropdown
hide_empty_metadata: true
hide_single_series: false
hide_single_unit: true
ignored_disaggregations: []
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/indicator-config
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: /tree/develop/data
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/meta
  translation_link: ''
  language: ''
  scopes:
    - national
    - global
    - source_1
  exclude_fields: []
  translated: false
indicator_tabs:
  tab_1: 'chart'
  tab_2: 'table'
  tab_3: hide
  tab_4: hide
languages:
  - en
languages_public: []
logos: []
map_layers: []
map_options:
  disaggregation_controls: true
  minZoom: 5
  maxZoom: 10
  tileURL: ''
  tileOptions:
    id: ''
    accessToken: ''
    attribution: ''
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'
menu:
  - path: /
    translation_key: general.home
    dropdown: []
  - path: /goals
    translation_key: general.goals
    dropdown: []
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  - path: /news
    translation_key: menu.updates
    dropdown: []
  - path: /faq
    translation_key: menu.faq
    dropdown: []
  - path: /about
    translation_key: menu.about
    dropdown: []
metadata_edit_url: metadata
metadata_tabs:
  - scope: global
    title: indicator.global_metadata
    description: indicator.global_metadata_blurb
  - scope: national
    title: indicator.national_metadata
    description: ''
  - scope: sources
    title: indicator.sources
    description: ''
meta_tags: []
news:
  category_links: true
observation_attributes: []
progress_status:
  status_heading: 'Target'
  status_help: ''
  status_types:
    - value: not_available
      label: status.progress_not_available
      image: assets/img/progress/not-available.png
      alt: status.progress_not_available
    - value: target_achieved
      label: status.progress_target_achieved
      image: assets/img/progress/target-achieved.png
      alt: status.progress_target_achieved
    - value: challenges_remain
      label: status.progress_challenges_remain
      image: assets/img/progress/challenges-remain.png
      alt: status.progress_challenges_remain
    - value: approaching_target
      label: status.progress_approaching_target
      image: assets/img/progress/approaching-target.png
      alt: status.progress_approaching_target
progressive_web_app:
  enabled: false
  name: ''
  short_name: ''
  precaching: false
proxy_indicators:
  label: ''
  description: ''
remote_data_prefix: 'https://cbsaua.github.io/data/'
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_indicator_count_label: ''
  disaggregation_tabs: true
  status_types:
    - value: notstarted
      label: status.no_data_available
      hide_on_goal_pages: false
    - value: complete
      label: status.reported_online
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
repository_url_data: 'https://github.com/open-sdg/open-sdg-data-starter'
repository_url_site: 'https://github.com/cbsaua/site'
search_index_boost: []
search_index_extra_fields: []
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/_data
  translation_link: ''
time_series_attributes:
  - field: COMMENT_TS
    label: indicator.footnote
  - field: DATA_LAST_UPDATE
    label: metadata_fields.national_data_update_url
use_new_config_forms: false
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''
